### ISSUE TITLE
Null on UnitOfWork Account Login

### ISSUE THREAD

**Issue by geekz-reno** [NonFactors/MVC5.Template#10]
![null_pointer](https://cloud.githubusercontent.com/assets/2031382/24456915/b4abdc34-14be-11e7-9133-f0703a50a304.png)
Hi, i just clone your project, doesn't change anything yet, but when i try to login, it say that UnitOfWork Account is null, is there any step that i missing? the database are already created using update-database.

Thank you for advice,

**Comment by Muchiachio** [comment]
Strange, doesn't happen to me, could you share a stack trace?

**Comment by geekz-reno** [comment]
Hi @Muchiachio i just change my connection from localdb to sqlexpress and it works, dont know why, maybe my localdb connection is still close, but why i can generate my table and seed data.

maybe for other that experience same error with me can change your connectionstring to sqlexpress or sql.

change your connection string to:

`<add name="Context" connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ArchrestServer#Local;User ID=xx;Password=xxxx" providerName="System.Data.SqlClient" />
        <add name="TestingContext" connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ArchrestServer_Testing#Local;User ID=xxxx;Password=xxxxx" providerName="System.Data.SqlClient" />`

and default connection to:

`<defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework">
            <parameters>
              <parameter value="Data Source=.\SQLEXPRESS; Integrated Security=True; MultipleActiveResultSets=True"/>
            </parameters>
        </defaultConnectionFactory>`

Thank your for sharing this awesome things, it teach me alot how to programming with c# and mvc.
Once again, thank you.
