### ISSUE TITLE
Use Partial class for Context and ObjectFactory

### ISSUE THREAD

**Issue by theit8514** [NonFactors/MVC5.Template#11]
Would it be possible to make Context and ObjectFactory classes into partials and create files for each area/controller/model? I am attempting to debug the scaffolding creation and the Scaffolder keeps creating the methods/properties in these two classes. Splitting these into partials should fix that issue since the Scaffolder can detect if the file exists.

DbSet.cs.t4:
```c#
﻿<#@ Template Language="C#" HostSpecific="True" Inherits="DynamicTransform" #> 
<#@ Output Extension="cs" #> 
using System; 
using System.ComponentModel.DataAnnotations; 
using System.Data.Entity; 
using MvcTemplate.Objects;
 
namespace MvcTemplate.Data.Core 
{ 
    public partial class Context 
    { 
        protected DbSet<<#= Model.Model #>> <#= Model.Models #> { get; set; } 
    } 
} 
```

ObjectFactory.cs.t4:
```c#
<#@ Template Language="C#" HostSpecific="True" Inherits="DynamicTransform" #>
<#@ Output Extension="cs" #>
using System;
using System.Collections.Generic;
using MvcTemplate.Components.Extensions;
using MvcTemplate.Objects;
using MvcTemplate.Tests.Objects;

namespace MvcTemplate.Tests
{
    public static partial class ObjectFactory
    {
        public static <#= Model.Model #> Create<#= Model.Model #>(int id = 0)
        {
            return new <#= Model.Model #>
            {
            };
        }
        public static <#= Model.View #> Create<#= Model.View #>(int id = 0)
        {
            return new <#= Model.View #>
            {
                Id = id
            };
        }
    }
}
```

**Comment by Muchiachio** [comment]
Yes, it's possible and is a nice idea that I didn't thought about. But I'm wondering if it is worth it?
Mainly because projects have hundreds of models, resulting in hundreds of partial classes times 2, wouldn't it impact search/compile times and experience? Just for a very rare debugging of scaffolding templates?

**Comment by theit8514** [comment]
Sorry for the delay in getting back to you on this suggestion.

I understand the use case is a little out there, but it could also be an issue for people trying to modify the templates and regenerate the output files.

Also, I think the optimization around compiling in partial classes is pretty good. For example, I set up the scaffolder to output about 400 partial classes with a single property each and the compilation time was still under a second.

**Comment by Muchiachio** [comment]
Again thank you for suggestion, but I still think it's too much noise for both the project and version control to keep as a default option.
