### ISSUE TITLE
Please guide to scaffolding

### ISSUE THREAD

**Issue by geekz-reno** [NonFactors/MVC5.Template#12]
Hai, please give me a guide to do scaffolding things, i already use default method to use scaffolding, but not generate as expected in visual studio.

many thanks

**Comment by Muchiachio** [comment]
I'm just using `MvcScaffolding` package, you can find various examples and full length explanations on the internet, like [here](http://blog.stevensanderson.com/2011/04/06/mvcscaffolding-overriding-the-t4-templates/) and [here](http://blog.stevensanderson.com/2011/01/13/scaffold-your-aspnet-mvc-3-project-with-the-mvcscaffolding-package/).

**Comment by Muchiachio** [comment]
Did it help?

**Comment by geekz-reno** [comment]
Hi @Muchiachio, sorry for late coz there assignment out of town for me. I already read link that you give and i abit confuse , but can you give me sample command to generate? sorry for this question.

**Comment by Muchiachio** [comment]
`scaffold module Tree Trees Woods`

**Comment by geekz-reno** [comment]
Many thanks @Muchiachio, ill try it first.
