### ISSUE TITLE
View from multiple tables

### ISSUE THREAD

**Issue by tareq2** [NonFactors/MVC5.Template#13]
Hi

This the first time to me in using the MVVM design and i hope some guide me on how to get a data from two tables (ex : Customer and his invoices) 

Thank you for sharing this opened source template.

**Comment by Muchiachio** [comment]
It's almost the same as in MVC, you would just add a list of invoices in customer class, but they both would be view classes, exposing only necessary fields.

```C#
public class CustomerView : BaseView
{
    public List<InvoiceView> Invoices { get; set; }
}

public class InvoiceView : BaseView
{
    public String Number { get; set; }
}
```

**Comment by tareq2** [comment]
Thank you very much
