### ISSUE TITLE
ok, i surrender

### ISSUE THREAD

**Issue by drogit** [NonFactors/MVC5.Template#14]
it appears you run a very tight and clean ship my friend.  so clean that i bet you are mad now at fact i posted a dumb question was unable find the password admin and cannot register  or register for that matter.  so did i miss reading it somewhere? or are we suppose to know what we are supposed to be doing.     i was really working hard on making the grid work today in my project but was thwarted by jquery errors.  yet another indication of my newbieness and perhaps in over head with this one..  apologies in advance for messing up you comment sections!

**Comment by Muchiachio** [comment]
It's included in `Configuration.cs` - the file which seeds the database with initial data.

**Comment by drogit** [comment]
many thanks for super quick answer (amazing!).  i did manage to find it before i saw your note.  now if only i can figure out how to implement my app into your template ... i will play for a while and see where i get.  i really like it, very clean UI. my compliments.
