### ISSUE TITLE
what jobs should i do, if i want to create a controller project for a new area

### ISSUE THREAD

**Issue by levonyang** [NonFactors/MVC5.Template#15]
could you give me some tips.
thanks in advance.

**Comment by Muchiachio** [comment]
You can generate most of the stuff using t4 scaffolding package. In the package manager console:
`scaffold module <ModelName> <ControllerName> [AreaName]`

And here's a real example: `scaffold module Client Clients Business`

**Comment by levonyang** [comment]
thanks for you quick response
i mean i want to move a area's controllers into a separate project

**Comment by Muchiachio** [comment]
They are already in separate project.

**Comment by levonyang** [comment]
if i want to add another new area, such as support.

**Comment by Muchiachio** [comment]
They would go to the same controllers project.

**Comment by levonyang** [comment]
ok. thanks

**Comment by levonyang** [comment]
@Muchiachio Are there any tutorials to explain more details about this project, i didn't find it by google.

**Comment by Muchiachio** [comment]
There is an introduction [here](https://www.codeproject.com/Articles/820836/ASP-NET-MVC-Template-introduction), but other than that it's just a template for MVC. You should be looking at resources for MVC framework itself.

**Comment by tareq2** [comment]
I suggest to add the introduction article to the readme file since it is very useful for the beginner

**Comment by Muchiachio** [comment]
It was added there as a place to ask questions, but in reality no one reads it so I removed it :)

**Comment by levonyang** [comment]
Good. thank you very much. @Muchiachio
