### ISSUE TITLE
Create a new controllers and new Areas?

### ISSUE THREAD

**Issue by cesarsan7** [NonFactors/MVC5.Template#20]
Before executing the "scaffolding module", what should I have created model and entity?

What default project should I use, at the time of executing the "scaffolding module"?

Where create a nuew area ?  
Example  i execute  scaffold module Cargo Cargos Configuracion , but get error 

view image 
![controller](https://user-images.githubusercontent.com/7913106/49451782-e9e06400-f7ad-11e8-83d8-9e6c605a6cd5.JPG)

Thank's

**Comment by cesarsan7** [comment]
Thanks , rebuilding project , function very well. i will like know which steps are the most adequate create a 
new controller and area, 

I executed the following steps, you tell me if I'm wrong

1.scaffold module Cargo Cargos Maestras 
2.Add attributes  class Cargo  in namespace xxx.Objects  
3.run update-database 
4.Add resources permission/Titles.resx 
5.Add resources controller/Titles.resx 
6.Add resources shared/Headers.resx
7.Add resources shared/Pages.resx
8.Add resources siteMap/Pages.resx
9.Edit file Mvc.sitemap, add new map/route controller 
10.Insert table permission 
11.Insert table Rolepermission 
12.Edit file views create, edit, delete and details for new controller

Tahnk you again.

**Comment by Muchiachio** [comment]
Yes, it's similar to
```
1) Add map call in ObjectMapper.cs
2) Add properties to model and view.
3) Add migrations to data and test projects.
4) Add privileges to Configuration.cs.
5) Add resources in Permissions - Action, Controller, Area (optional).
6) Add resources for Page and Headers.
7) Add resource to SiteMap.
8) Add resources for all views in Views folder.
9) Add sitemap to Mvc.sitemap
10) Add privileges to initial data tests.
```

**Comment by cesarsan7** [comment]
Thank you, for your help, I will use this project as a template for a personal project, then you may have new questions. thank you.
