### ISSUE TITLE
Add views master and detail

### ISSUE THREAD

**Issue by cesarsan7** [NonFactors/MVC5.Template#21]
Hello @Muchiachio 

Hi, I'm excited with this template, i very like , I'm new worked with asp net, already  have various controllers functioned.
Now i need create one view master /details with options create, edit ,and delete. 

Can you help me with an example of how I can do this?

vey thanks for collaboration , what your haved with this open source. 

Thanks.

**Comment by Muchiachio** [comment]
Is there anything preventing you from doing that or it's just your first project?

If you are still learning asp net, I would recommend not using this template and doing things from scratch using all the available tutorials and learning material online. This template is targeted towards more experienced developers who have already wrote a few projects and want to have a base for faster development.

**Comment by cesarsan7** [comment]
Sorry, I had not been able to answer before.

No, it's not my first project, I just wanted saber and you had some example, the truth, I think you have very well organized the code of the project, and I want to continue, with the order that you have.

Thank you very much, if I am using the project, as a basis for a personal project, thank you very much for your contributions.
