### ISSUE TITLE
Call stored procedure or View using unit of work

### ISSUE THREAD

**Issue by cesarsan7** [NonFactors/MVC5.Template#22]
Hello , 
Very thanks for  shared this template source ,  i have a questions,  i like know  how call stored procedure and map  result in class view .

At this moment I already managed to call the stored procedure that does not return results and works well, but now I would like to call a view, get the results and map them in a class view. Thank you

![controller](https://user-images.githubusercontent.com/7913106/51142176-29708600-1819-11e9-9aca-06997752f882.JPG)

**Comment by Muchiachio** [comment]
I'm not sure, maybe [this](https://stackoverflow.com/questions/36197009/mapping-stored-procedures-to-views) helps.

**Comment by cesarsan7** [comment]
Thanks for answering ;)
