### ISSUE TITLE
Excuse me whether you can add an API program

### ISSUE THREAD

**Issue by leeolevis** [NonFactors/MVC5.Template#3]
Excuse me whether you can add an API program
I will learn more, thank you！

**Comment by Muchiachio** [comment]
Hi, what do you mean by API program?
If you are looking for a WebAPI template, you would be better off using the default visual studio template, because this template adds way too much code needed to run a WebAPI project.

**Comment by Muchiachio** [comment]
Closing as there is no answer. If you have any more question feel free to ask them at [code project's comments section](http://www.codeproject.com/Articles/820836/ASP-NET-MVC-Template-introduction).
