### ISSUE TITLE
Request the change of the model's key from int to guid

### ISSUE THREAD

**Issue by coolman2135** [NonFactors/MVC5.Template#8]
Hello, first of all, I'd like to thanks for your project. And now, I have a request to change the model's key from int to guid, because it will works well when the database transfer, so could pls kindly help to change the key of the models from int to guid? Then, when the model mapping to the database, the data type of the table  should change from int32 to guid. Thanks in advance!

**Comment by Muchiachio** [comment]
This project used to have `GUID` ids, so you could start by looking at [this commit](https://github.com/NonFactors/MVC5.Template/commit/f9fb6e05719d35a79cbd8d20eedd0a6a1c7a2d21) to see what has changed. Or even try to revert it using git.

**Comment by Muchiachio** [comment]
Did it help?

**Comment by coolman2135** [comment]
I don't know how to download that special version.

发自我的 iPhone

**Comment by Muchiachio** [comment]
If you are fine with just downloading older version you can do it from [here](https://github.com/NonFactors/MVC5.Template/archive/ca4b2b6ef600a5aaab417cec4fb14fc87ff0a9a6.zip).

**Comment by coolman2135** [comment]
First, Thanks for your help, could you pls give a simple sample to get the special commit?






At 2016-12-18 17:26:44, "Muchiachio" <notifications@github.com> wrote:


If you are fine with just downloading older version you can do it from here.

**Comment by Muchiachio** [comment]
What do you mean by simple sample? I gave you a download link of the source for that commit.

**Comment by coolman2135** [comment]
Yes, I have got the code from your link. I mean how to find it on the github.




At 2016-12-21 20:38:04, "Muchiachio" <notifications@github.com> wrote:


What do you mean by simple sample? I gave you a download link of the source for that commit.

**Comment by Muchiachio** [comment]
[This commit](https://github.com/NonFactors/MVC5.Template/commit/f9fb6e05719d35a79cbd8d20eedd0a6a1c7a2d21) changed from guid to int. If you want to see the source code press `Browse files`.
And [this commit](https://github.com/NonFactors/MVC5.Template/tree/ca4b2b6ef600a5aaab417cec4fb14fc87ff0a9a6) was the last one with guid ids.

**Comment by coolman2135** [comment]
My question is how to find this commit in the brower files.

**Comment by Muchiachio** [comment]
I found it using git commands locally, another way would be to try searching through [github commits](https://github.com/NonFactors/MVC5.Template/commits/develop), but it's slow.

**Comment by coolman2135** [comment]
Yes,I'd like to know for that special commit version, does it contain the newest feature?





At 2016-12-21 21:16:44, "Muchiachio" <notifications@github.com> wrote:


I found it using git commands locally, another way would be to try searching through github commits, but it's slow.

**Comment by Muchiachio** [comment]
No it does not, it the newest version before the migration from guid ids happened.
If you want to have the latest code, but with guid ids, you will have to revert that change using that commit.

**Comment by coolman2135** [comment]
ok，thanks，but I can not find the commit No in the search function.

发自我的 iPhone

**Comment by Muchiachio** [comment]
I linked the commits in previous comments, I'm not sure if I can help you with github issues.

**Comment by coolman2135** [comment]
yes，it does，thanks.

发自我的 iPhone

**Comment by coolman2135** [comment]
Hello,




I'm using your framework now, however, in this project, the number of the users will be a little large. Therefore, is there something wick in the concurrency problem? Or what aspect we can do to improve the high concurrency of your framework?






Thanks





在 2016-12-21 23:14:48，"Muchiachio" <notifications@github.com> 写道：


Closed #8.

**Comment by Muchiachio** [comment]
Did you identify which parts are not working for you?

**Comment by coolman2135** [comment]
no，I means we will use your framework to do a high concurrency system. I warry about the handle ability.

发自我的 iPhone

**Comment by Muchiachio** [comment]
First of all it's not a framework, it' just a MVC template. It has some sample modules like users and their roles, but other than that you can write your own controllers and services in a high concurrent manner for MVC5.

**Comment by coolman2135** [comment]
How do you manage the less files？I found the changs in them did not work.

发自我的 iPhone

**Comment by Muchiachio** [comment]
I'm using web essentials extension, or any other less compiler extension.

**Comment by coolman2135** [comment]
Yes，in asp.net，when we changed the less files ，the css files did not change accordingly.

发自我的 iPhone
