### ISSUE TITLE
Login Session

### ISSUE THREAD

**Issue by coolman2135** [NonFactors/MVC5.Template#9]
When we login in the system, there is nothing about the user info written into the session, is there any special purpose?

**Comment by Muchiachio** [comment]
Because default MVC login only saves user identification key to the cookie.
In this case only user id is saved.

**Comment by coolman2135** [comment]
Ok. For now, could you pls help to give me a special version which use MySql Database?






At 2017-01-17 14:59:05, "Muchiachio" <notifications@github.com> wrote:


Because default MVC login only saves user identification key to the cookie.
In this case only user id is saved.

**Comment by Muchiachio** [comment]
I don't have a version to use MySql database, but it should be relatively easy to change using [MySql docs](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html).
